### PR TITLE
Toobar toggler update

### PR DESCRIPTION
**Pull request by Fedik**
I have removed addittional script.
And changed toolbar buttons to handle visibility "on key".
Now it just:
```php
$toolbar->trash('articles.trash')
    ->listCheck(true)
    ->toggleHiddenOnKey('Shift');

$toolbar->delete('articles.delete')
    ->message('JGLOBAL_CONFIRM_DELETE')
    ->listCheck(true)
    ->hidden(true)
    ->toggleHiddenOnKey('Shift');
```

However there still a small styling issue, when the button is first it will jump a bit

### CODE REVIEW

**Comment by HLeithner** [comment]
not really happy with this. this reduces down to only be usable in toolbar which is not really needed, it can also be used for hidden help text or other this if it is not bind to the toolbar, actually any menu item too.

I see this thing more for a foundation for more complex interfaces, at some point when you create complex software like bookkeeping software or CRM faster workflows for more experienced users should be possible

**Comment by Fedik** [comment]
Look, realisticaly, we have available only 3 buttons: Alt, Ctrl, Shift. How much variants we can get from it? :wink: 

To have something advanced, we need to include a shortcut library. And that another level.
Addittionaly the feature should be usable with 1 hand.

**Comment by HLeithner** [comment]
realistically I see also combinations and other keys like Numlock and Roll. Meta key is also possible. looking at what google or microsoft does with there in browser apps shows you what's possible.

**Comment by Fedik** [comment]
For more combinations we would need to use a shortcut library.

And:
```html
<div data-toggle-hidden-on-key="Ctrl+1">
  Visible by default
</div>
<div hidden data-toggle-hidden-on-key="Ctrl+1">
  Hidden by default
</div>
```

**Pull request closed without merging**
